# Generated by Django 4.1.6 on 2023-03-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports_goods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="goods",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Equipment_name", models.CharField(max_length=30)),
                ("Sport", models.CharField(max_length=30)),
                ("Possessed_by", models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name="students",
            name="Phone_number",
            field=models.IntegerField(unique=True),
        ),
    ]
