# Generated by Django 4.1.6 on 2023-03-31 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sports_goods", "0002_goods_alter_students_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goods",
            old_name="Id",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="students",
            name="Item1",
            field=models.ForeignKey(
                blank=True,
                db_column="Item1",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item1_students",
                to="sports_goods.goods",
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="Item2",
            field=models.ForeignKey(
                blank=True,
                db_column="Item2",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item2_students",
                to="sports_goods.goods",
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="Item3",
            field=models.ForeignKey(
                blank=True,
                db_column="Item3",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item3_students",
                to="sports_goods.goods",
            ),
        ),
    ]
