# Generated by Django 4.1.6 on 2023-04-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports_goods", "0007_students_delete_ptudent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="Phone_number",
            field=models.BigIntegerField(unique=True),
        ),
    ]
