# Generated by Django 4.1.6 on 2023-04-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports_goods", "0008_alter_students_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="Enrollment_number",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
