# Generated by Django 4.1.6 on 2023-04-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports_goods", "0009_alter_students_enrollment_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="Fine",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, null=True
            ),
        ),
    ]
