# Generated by Django 4.1.6 on 2023-04-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sports_goods", "0012_alter_ptudents_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ptudents",
            table="User1",
        ),
    ]
