# Generated by Django 4.1.6 on 2023-04-01 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sports_goods", "0013_alter_ptudents_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ptudents",
            table="User",
        ),
    ]
