# Generated by Django 4.1.6 on 2023-04-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sports_goods", "0016_students_password"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="goods",
            table="Items",
        ),
    ]
