# Generated by Django 4.1.6 on 2023-04-03 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sports_goods", "0017_alter_goods_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="Possessed_by",
            field=models.ForeignKey(
                blank=True,
                db_column="Possessed_by",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="possess",
                to="sports_goods.students",
            ),
        ),
    ]
