# Generated by Django 4.1.6 on 2023-04-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sports_goods", "0018_alter_goods_possessed_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students",
            name="Item3",
        ),
    ]
