# Generated by Django 4.1.6 on 2023-04-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports_goods", "0019_remove_students_item3"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="Item3",
            field=models.DateTimeField(null=True),
        ),
    ]
