# Generated by Django 4.1.6 on 2023-04-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sports_goods", "0020_students_item3"),
    ]

    operations = [
        migrations.RenameField(
            model_name="students",
            old_name="Item3",
            new_name="book_time",
        ),
    ]
