# Generated by Django 4.1.6 on 2023-04-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports_goods", "0021_rename_item3_students_book_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="book_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
