# Generated by Django 4.1.6 on 2023-04-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports_goods", "0022_alter_students_book_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="Fine",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=7, null=True
            ),
        ),
    ]
