# Generated by Django 4.1.6 on 2023-04-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "sports_goods",
            "0026_rename_enrollment_number_transaction_enrollment_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="transaction",
            table="Transaction1",
        ),
    ]
