# Generated by Django 4.1.6 on 2023-04-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports_goods", "0027_alter_transaction_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="Enrollment_number",
            field=models.BigIntegerField(),
        ),
    ]
