# Generated by Django 4.1.6 on 2023-04-30 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sports_goods", "0028_alter_transaction_enrollment_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.ForeignKey(
                db_column="id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="possess",
                to="sports_goods.goods",
            ),
        ),
    ]
